name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:
  Push_Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Resolve Dependencies
        run: yarn

      - name: Playwright install
        run: yarn playwright install

      - name: Build production
        run: yarn build

      - name: Deploy production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GATSBY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
